---
services:
  kestra-postgres:
    image: postgres:17
    container_name: kestra-postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: $KESTRA_POSTGRES_PASSWORD
    volumes:
      - $DATA/kestra/postgres:/var/lib/postgresql/data

  kestra:
    image: kestra/kestra:v0.20.13
    container_name: kestra
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: server standalone
    user: "root"
    depends_on:
      kestra-postgres:
        condition: service_started
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra-postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: $KESTRA_POSTGRES_PASSWORD
        kestra:
          server:
            basicAuth:
              enabled: false
              username: $EMAIL
              password: $KESTRA_USER_PASSWORD
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: https://kestra.$DOMAIN
    volumes:
      - $DATA/kestra/storage:/app/storage
      - /tmp/kestra-wd:/tmp/kestra-wd
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kestra.rule=Host(`kestra.$DOMAIN`)"
      - "traefik.http.routers.kestra.entrypoints=websecure"
      - "traefik.http.routers.kestra.tls.certresolver=myresolver"
      - "traefik.http.routers.kestra.priority=10"
      - "traefik.http.services.kestra.loadbalancer.server.port=8080"
      - "traefik.http.routers.kestra.middlewares=authelia@docker"
      - "homepage.group=Admin"
      - "homepage.name=Kestra"
      - "homepage.icon=sh-kestra"
      - "homepage.weight=800"
      - "homepage.href=https://kestra.$DOMAIN"
