---
version: '3.8'

include:
  # - ./authentik/compose.yml
  - ./adguardhome/compose.yml
  # - ./lancache/compose.yml
  - ./homeassistant/compose.yml
  # - ./mailserver/compose.yml
  - ./media/compose.yml
  # - ./mealie/compose.yml
  - ./paperless/compose.yml
  # - ./twingate/compose.yml

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_SCHEDULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:v2.10.7
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--global.sendAnonymousUsage=false'
      - '--global.checkNewVersion=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entryPoints.http=true'
      - '--entryPoints.http.address=:80/tcp'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
      - '--entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.http.forwardedHeaders.insecure=false'
      - '--entryPoints.http.proxyProtocol.insecure=false'
      - '--entryPoints.https=true'
      - '--entryPoints.https.address=:443/tcp'
      - '--entryPoints.https.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.https.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.https.forwardedHeaders.insecure=false'
      - '--entryPoints.https.proxyProtocol.insecure=false'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.cloudflare.acme.email=${PUBLIC_EMAIL}'
      - "--certificatesresolvers.cloudflare.acme.storage=/acme/acme-cloudflare.json"
    environment:
      - TZ
      - CF_API_EMAIL=${PUBLIC_EMAIL}
      - CF_API_KEY
      # - CF_DNS_API_TOKEN
    ports:
      - ${LOCAL_IP}:80:80
      - ${LOCAL_IP}:443:443
    volumes:
      - ${DATA}/traefik/config:/config
      - ${DATA}/traefik/acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.${LOCAL_DOMAIN}`)'
      - 'traefik.http.routers.api.entryPoints=https'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.certresolver=cloudflare'
      - 'traefik.http.routers.api.service=api@internal'
      # - 'traefik.http.routers.api.middlewares=authelia@docker'

  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`portainer.${LOCAL_DOMAIN}`)'
      - 'traefik.http.routers.portainer.entryPoints=https'
      - 'traefik.http.routers.portainer.tls=true'
      - 'traefik.http.routers.portainer.tls.certresolver=cloudflare'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

  changedetection:
    image: lscr.io/linuxserver/changedetection.io:0.45.20230906
    container_name: changedetection
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - BASE_URL=https://change.${LOCAL_DOMAIN}/
    volumes:
      - ${DATA}/changedetection:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.change.rule=Host(`change.${LOCAL_DOMAIN}`)'
      - 'traefik.http.routers.change.entrypoints=https'
      - 'traefik.http.routers.change.tls=true'
      - 'traefik.http.routers.change.tls.certresolver=cloudflare'
      # - 'traefik.http.routers.change.middlewares=authelia@docker'
      - 'traefik.http.services.change.loadbalancer.server.port=5000'
