---
version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:2023.8.0
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    env_file:
      - .env
