---
version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:2023.8.2
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    env_file:
      - .env

  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DATA}/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:14
    container_name: teleport
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DATA}/teleport/config:/etc/teleport
      - ${DATA}/teleport/data:/var/lib/teleport
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
      - "traefik.http.routers.teleport-http.entrypoints=web"
      - "traefik.http.routers.teleport-http.rule=HostRegexp(`${DOMAIN}`, `{subhost:[a-z]+}.${DOMAIN}`)"
      - "traefik.http.routers.teleport-https.entrypoints=websecure"
      - "traefik.http.routers.teleport-https.rule=HostRegexp(`${DOMAIN}`, `{subhost:[a-z]+}.${DOMAIN}`)"
      - "traefik.http.routers.teleport-https.tls=true"
      - "traefik.http.routers.teleport-https.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.${DOMAIN}"

  homepage:
    image: ghcr.io/benphelps/homepage:v0.7.0
    container_name: homepage
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DATA}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  homeassistant:
    image: homeassistant/home-assistant:2023.9
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${DATA}/homeassistant:/config

  primelooter:
    image: ghcr.io/srhinos/primelooter:latest
    container_name: primelooter
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${DATA}/primelooter/cookies.txt:/app/cookies.txt
      - ${DATA}/primelooter/publishers.txt:/app/publishers.txt
      - ${DATA}/primelooter/game_codes.txt:/app/game_codes.txt
