---
include:
  - homepage/compose.yml
  - authentik/compose.yml
  - adguardhome/compose.yml
  - homeassistant/compose.yml
  - homepage/compose.yml
  # - mailcow/docker-compose.yml
  # - mealie/compose.yml
  - media/compose.yml
  - paperless/compose.yml
  # - traccar/compose.yml

services:
  cloudflared:
    image: cloudflare/cloudflared:2024.11.1
    container_name: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: tunnel --no-autoupdate run
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TUNNEL_TOKEN: $TUNNEL_TOKEN

  whatsupdocker:
    image: getwud/wud:7.1.1
    container_name: wud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  code-server:
    image: lscr.io/linuxserver/code-server:4.95.3
    container_name: code-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      PROXY_DOMAIN: code.$DOMAIN
      DEFAULT_WORKSPACE: /config/workspace
    volumes:
      - $DATA/code-server:/config
      - /mnt/user/docker-nas:/config/workspace/docker-nas
      - /mnt/user/appdata:/config/workspace/appdata
