---
version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_SCHEDULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:2.11.1
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--global.sendAnonymousUsage=false'
      - '--global.checkNewVersion=false'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.watch=true'
      - '--entryPoints.http=true'
      - '--entryPoints.http.address=:80/tcp'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
      - '--entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.http.forwardedHeaders.insecure=false'
      - '--entryPoints.http.proxyProtocol.insecure=false'
      - '--entryPoints.https=true'
      - '--entryPoints.https.address=:443/tcp'
      - '--entryPoints.https.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.https.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/16,192.168.0.0/16,fc00::/7'
      - '--entryPoints.https.forwardedHeaders.insecure=false'
      - '--entryPoints.https.proxyProtocol.insecure=false'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.cloudflare.acme.email=$EMAIL'
      - "--certificatesresolvers.cloudflare.acme.storage=/acme/acme-cloudflare.json"
    environment:
      - TZ
      - CLOUDFLARE_EMAIL=$EMAIL
      - CLOUDFLARE_API_KEY
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DATA}/traefik/config:/config
      - ${DATA}/traefik/acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)'
      - 'traefik.http.routers.api.entryPoints=https'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.certresolver=cloudflare'
      - 'traefik.http.routers.api.service=api@internal'

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    environment:
      - DOCKGE_STACKS_DIR=/mnt/user/docker-nas
    volumes:
      - ${DATA}/dockge/data:/app/data
      - /mnt/user/docker-nas:/mnt/user/docker-nas
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    ports:
      - 5001:5001
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.dockge.rule=Host(`dockge.${DOMAIN}`)'
      - 'traefik.http.routers.dockge.entryPoints=https'
      - 'traefik.http.routers.dockge.tls=true'
      - 'traefik.http.routers.dockge.tls.certresolver=cloudflare'
      - 'traefik.http.services.dockge.loadbalancer.server.port=5001'

networks:
  proxy:
    external: true
