---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.2.0
    container_name: mealie
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUIG
      - PGID
      - TZ
      - ALLOW_SIGNUP=false
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${DOMAIN}
    volumes:
      - ${DATA}/mealie:/app/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`mealie.${DOMAIN}`)
      - traefik.http.routers.mealie.entryPoints=https
      - traefik.http.routers.mealie.tls=true
      - traefik.http.routers.mealie.tls.certresolver=cloudflare
      - traefik.http.services.mealie.loadbalancer.server.port=9000
