---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.3.0
    container_name: mealie
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUIG
      - PGID
      - TZ
      - ALLOW_SIGNUP=false
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${DOMAIN}
    volumes:
      - ${DATA}/mealie:/app/data
