---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.1
    container_name: mealie
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ALLOW_SIGNUP: false
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.$DOMAIN
    volumes:
      - $DATA/mealie:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`mealie.$DOMAIN`)"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls.certresolver=myresolver"
      - "traefik.http.routers.mealie.priority=10"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "homepage.group=Home"
      - "homepage.name=Mealie"
      - "homepage.icon=sh-mealie"
      - "homepage.weight=200"
      - "homepage.href=https://mealie.$DOMAIN/"
      - "homepage.widget.type=mealie"
      - "homepage.widget.url=http://mealie:9000"
      - "homepage.widget.key=$HOMEPAGE_MEALIE_KEY"
      - "homepage.widget.version=2"
