version: "3.8"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    env_file:
      - ../.env
    environment:
      - ALLOW_SIGNUP=false
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${DOMAIN}
    volumes:
      - ${DATA}/mealie:/app/data/
