---
version: '3.8'

services:
  omada-controller:
    image: mbentley/omada-controller:5.12
    container_name: omada-controller
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    env_file:
      - ../.env
    environment:
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815s
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      # - SSL_CERT_NAME=tls.crt
      # - SSL_KEY_NAME=tls.keysss
    volumes:
      - ${DATA}/omada-data:/opt/tplink/EAPController/data
      - ${DATA}/omada-logs:/opt/tplink/EAPController/logss
