---
services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.13-alpine
    container_name: uptimekuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUIG
      - PGID
      - TZ
    volumes:
      - ${DATA}/uptimekuma:/app/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.rule=Host(`status.${DOMAIN}`)
      - traefik.http.routers.uptimekuma.entryPoints=https
      - traefik.http.routers.uptimekuma.tls=true
      - traefik.http.routers.uptimekuma.tls.certresolver=cloudflare
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
