version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - $DATA/prometheus:/prometheus
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.prometheus.rule=Host(`prometheus.$DOMAIN`)
      - traefik.http.routers.prometheus.entryPoints=https
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=cloudflare
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
networks:
  proxy:
    external: true
