---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:0.21.1
    container_name: speedtest-tracker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID
      - PGID
      - TZ
      - APP_KEY
      - APP_URL=speed.${DOMAIN}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE
      - SPEEDTEST_SERVERS
      # - DB_HOST= #optional
      # - DB_PORT= #optional
      # - DB_DATABASE= #optional
      # - DB_USERNAME= #optional
      # - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=${TZ}
      # - PRUNE_RESULTS_OLDER_THAN=0 #optional
    volumes:
      - ${DATA}/speedtest-tracker/data:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.speedtest.rule=Host(`speed.${DOMAIN}`)
      - traefik.http.routers.speedtest.entryPoints=https
      - traefik.http.routers.speedtest.tls=true
      - traefik.http.routers.speedtest.tls.certresolver=cloudflare
      - traefik.http.services.speedtest.loadbalancer.server.port=80
