---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2024.12.4
    container_name: homeassistant
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    network_mode: host
    # extra_hosts:
      # - host.docker.internal:host-gateway
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    # devices:
    # - /path/to/device:/path/to/device
    volumes:
      - $DATA/homeassistant:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`ha.$DOMAIN`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      - "traefik.http.routers.homeassistant.priority=10"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "homepage.group=Home"
      - "homepage.name=Home Assistant"
      - "homepage.icon=sh-home-assistant"
      - "homepage.weight=0"
      - "homepage.href=https://ha.$DOMAIN/"
      - "homepage.widget.type=homeassistant"
      - "homepage.widget.url=http://$IP:8123"
      - "homepage.widget.key=$HOMEPAGE_HOMEASSISTANT_KEY"

  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    container_name: frigate
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges=true
      - apparmor=unconfined
      - systempaths=unconfined
    shm_size: 128mb
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri:/dev/dri
    # ports:
      # - 5000:5000
      # - 8971:8971
      # - 8554:8554
      # - 8555:8555/tcp
      # - 8555:8555/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA/frigate/config:/config
      - $DATA/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 510000000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.$DOMAIN`)"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.tls.certresolver=myresolver"
      - "traefik.http.routers.frigate.priority=10"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
      - "homepage.group=Home"
      - "homepage.name=Frigate"
      - "homepage.icon=sh-frigate"
      - "homepage.weight=100"
      - "homepage.href=https://frigate.$DOMAIN/"
      - "homepage.widget.type=frigate"
      - "homepage.widget.url=http://frigate:5000"
      - "homepage.widget.fields=['cameras', 'uptime']"
