---
version: '3.9'

services:
  homeassistant:
    image: homeassistant/home-assistant:2024.1
    container_name: homeassistant
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    volumes:
      - ${DATA}/homeassistant:/config
