---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2024.10.3
    container_name: homeassistant
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    environment:
      - PUIG
      - PGID
      - TZ
    # devices:
    # - /path/to/device:/path/to/device
    volumes:
      - ${DATA}/homeassistant:/config

  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    container_name: frigate
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges:true
    shm_size: 128mb
    environment:
      - PUIG
      - PGID
      - TZ
      - FRIGATE_RTSP_PASSWORD
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/frigate/config:/config
      - ${DATA}/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 510000000
