---
services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${DATA}/jellyfin:/config
      - /mnt/user/Serien:/data/serien
      - /mnt/user/Filme:/data/filme
    devices:
      - /dev/dri:/dev/dri

  jellyseerr:
    image: fallenbagel/jellyseerr:2.1.0
    container_name: jellyseerr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/jellyseerr:/app/config

  prowlarr:
    image: linuxserver/prowlarr:1.27.0
    container_name: prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/prowlarr:/config

  radarr:
    image: linuxserver/radarr:5.15.1
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/radarr:/config
      - /mnt/user/Filme:/movies
      - /mnt/user/Downloads:/downloads

  sonarr:
    image: linuxserver/sonarr:4.0.11
    container_name: sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/sonarr:/config
      - /mnt/user/Serien:/tv
      - /mnt/user/Downloads:/downloads

  readarr:
    image: linuxserver/readarr:0.4.5-develop
    container_name: readarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/readarr:/config
      - /mnt/user/eBooks:/books
      - /mnt/user/Downloads:/downloads

  calibre-web:
    image: linuxserver/calibre-web:0.6.24
    container_name: calibre-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ${DATA}/calibre-web:/config
      - /mnt/user/eBooks:/books

  sabnzbd:
    image: linuxserver/sabnzbd:4.4.0
    container_name: sabnzbd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/sabnzbd:/config
      - /mnt/user/Downloads:/downloads

  pyload-ng:
    image: linuxserver/pyload-ng:0.5.0
    container_name: pyload-ng
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/pyload-ng:/config
      - /mnt/user/Downloads:/downloads
