version: "3.8"
services:
  jellyfin:
    image: linuxserver/jellyfin:10.8.13
    container_name: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${DATA}/jellyfin:/config
      - /mnt/user/Serien:/data/serien
      - /mnt/user/Filme:/data/filme
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jellyfin.rule=Host(`media.${DOMAIN}`)
      - traefik.http.routers.jellyfin.entryPoints=https
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=cloudflare
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    networks:
      - proxy
  jellyseerr:
    image: fallenbagel/jellyseerr:1.8.1
    container_name: jellyseerr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/jellyseerr:/app/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jellyseerr.rule=Host(`request.${DOMAIN}`)
      - traefik.http.routers.jellyseerr.entryPoints=https
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.routers.jellyseerr.tls.certresolver=cloudflare
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
    networks:
      - proxy
  prowlarr:
    image: linuxserver/prowlarr:1.16.2
    container_name: prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/prowlarr:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.http.routers.prowlarr.entryPoints=https
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=cloudflare
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    networks:
      - proxy
  radarr:
    image: linuxserver/radarr:5.4.6
    container_name: radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/radarr:/config
      - /mnt/user/Filme:/movies
      - /mnt/user/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entryPoints=https
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    networks:
      - proxy
  sonarr:
    image: linuxserver/sonarr:4.0.4
    container_name: sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/sonarr:/config
      - /mnt/user/Serien:/tv
      - /mnt/user/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entryPoints=https
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=cloudflare
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    networks:
      - proxy
  readarr:
    image: linuxserver/readarr:0.3.23-develop
    container_name: readarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/readarr:/config
      - /mnt/user/eBooks:/books
      - /mnt/user/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.readarr.rule=Host(`readarr.${DOMAIN}`)
      - traefik.http.routers.readarr.entryPoints=https
      - traefik.http.routers.readarr.tls=true
      - traefik.http.routers.readarr.tls.certresolver=cloudflare
      - traefik.http.services.readarr.loadbalancer.server.port=8787
    networks:
      - proxy
  calibre-web:
    image: linuxserver/calibre-web:0.6.21
    container_name: calibre-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ${DATA}/calibre-web:/config
      - /mnt/user/eBooks:/books
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.calibre.rule=Host(`calibre.${DOMAIN}`)
      - traefik.http.routers.calibre.entryPoints=https
      - traefik.http.routers.calibre.tls=true
      - traefik.http.routers.calibre.tls.certresolver=cloudflare
      - traefik.http.services.calibre.loadbalancer.server.port=8083
    networks:
      - proxy
  sabnzbd:
    image: linuxserver/sabnzbd:4.2.3
    container_name: sabnzbd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/sabnzbd:/config
      - /mnt/user/Downloads:/downloads
    ports:
      - 8081:8080
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.routers.sabnzbd.entryPoints=https
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.tls.certresolver=cloudflare
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    networks:
      - proxy
  pyload-ng:
    image: linuxserver/pyload-ng:0.5.0
    container_name: pyload-ng
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/pyload-ng:/config
      - /mnt/user/Downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.pyload.rule=Host(`pyload.${DOMAIN}`)
      - traefik.http.routers.pyload.entryPoints=https
      - traefik.http.routers.pyload.tls=true
      - traefik.http.routers.pyload.tls.certresolver=cloudflare
      - traefik.http.services.pyload.loadbalancer.server.port=8000
    networks:
      - proxy
networks:
  proxy:
    external: true
