---
version: '3.8'

services:
  paperless-redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/paperless/redis:/data

  paperless-mariadb:
    image: mariadb:11
    container_name: paperless-mariadb
    restart: unless-stopped
    volumes:
      - ${DATA}/paperless/mariadb:/var/lib/mysql
    env_file:
      - ../.env
      - .env

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.1
    container_name: paperless-ngx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - paperless-redis
      - paperless-gotenberg
      - paperless-tika
    env_file:
      - ../.env
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${DATA}/paperless/data:/usr/src/paperless/data
      - /mnt/user/Paperless-Media:/usr/src/paperless/media
      - /mnt/user/Paperless-Export:/usr/src/paperless/export
      - /mnt/user/Paperless-Import:/usr/src/paperless/consume
    ports:
      - 8000:8000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.paperless.rule=Host(`paperless.${LOCAL_DOMAIN}`)'
      - 'traefik.http.routers.paperless.entryPoints=https'
      - 'traefik.http.routers.paperless.tls=true'
      - 'traefik.http.routers.paperless.tls.certresolver=cloudflare'
      - 'traefik.http.services.paperless.loadbalancer.server.port=8000'

  paperless-gotenberg:
    image: gotenberg/gotenberg:7.10
    container_name: paperless-gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  paperless-tika:
    image: ghcr.io/paperless-ngx/tika:2.9.0-minimal
    container_name: paperless-tika
    restart: unless-stopped
