---
version: '3.8'

services:
  paperless-redis:
    image: redis:7
    container_name: paperless-redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/paperless/redis:/data

  paperless-mariadb:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ${DATA}/paperless/mariadb:/var/lib/mysql
    env_file:
      - ../.env
      - .env

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - paperless-redis
      - gotenberg
      - tika
    env_file:
      - ../.env
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${DATA}/paperless/data:/usr/src/paperless/data
      - /mnt/user/Paperless-Media:/usr/src/paperless/media
      - /mnt/user/Paperless-Export:/usr/src/paperless/export
      - /mnt/user/Paperless-Import:/usr/src/paperless/consume
    ports:
      - 8000:8000

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
