---
services:
  orcaslicer:
    image: lscr.io/linuxserver/orcaslicer:latest
    container_name: orcaslicer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${DATA}/orcaslicer:/config
    ports:
      - 3000:3000
      - 3001:3001
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.orcaslicer.rule=Host(`slicer.${DOMAIN}`)'
      - 'traefik.http.routers.orcaslicer.entryPoints=https'
      - 'traefik.http.routers.orcaslicer.tls=true'
      - 'traefik.http.routers.orcaslicer.tls.certresolver=cloudflare'
      - 'traefik.http.services.orcaslicer.loadbalancer.server.port=3000'
    