---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    container_name: homepage
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DATA/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
