---
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.54
    container_name: adguardhome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUIG
      - PGID
      - TZ
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      # - 68:68/udp
      # - 8088:80/tcp
      # - 8444:443/tcp
      # - 8444:443/udp
      # - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ${DATA}/adguard/conf:/opt/adguardhome/conf
      - ${DATA}/adguard/work:/opt/adguardhome/work
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)
      - traefik.http.routers.adguard.entryPoints=https
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.tls.certresolver=cloudflare
      - traefik.http.services.adguard.loadbalancer.server.port=80
