---
version: '3.8'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.43
    container_name: adguardhome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/adguard/conf:/opt/adguardhome/conf
      - ${DATA}/adguard/work:/opt/adguardhome/work
    ports:
      - ${LOCAL_IP}:53:53/tcp
      - ${LOCAL_IP}:53:53/udp
      - ${LOCAL_IP}:67:67/udp
      # - ${LOCAL_IP}:68:68/udp
      # - ${LOCAL_IP}:80:80/tcp
      # - ${LOCAL_IP}:443:443/tcp
      # - ${LOCAL_IP}:443:443/udp
      # - ${LOCAL_IP}:3000:3000/tcp
      - ${LOCAL_IP}:853:853/tcp
      - ${LOCAL_IP}:784:784/udp
      - ${LOCAL_IP}:853:853/udp
      - ${LOCAL_IP}:8853:8853/udp
      - ${LOCAL_IP}:5443:5443/tcp
      - ${LOCAL_IP}:5443:5443/udp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adguard.rule=Host(`adguard.${LOCAL_DOMAIN}`)'
      - 'traefik.http.routers.adguard.entryPoints=https'
      - 'traefik.http.routers.adguard.tls=true'
      - 'traefik.http.routers.adguard.tls.certresolver=cloudflare'
      - 'traefik.http.services.adguard.loadbalancer.server.port=80'
