version: "3.8"
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.45
    container_name: adguardhome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DATA}/adguard/conf:/opt/adguardhome/conf
      - ${DATA}/adguard/work:/opt/adguardhome/work
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)
      - traefik.http.routers.adguard.entryPoints=https
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.tls.certresolver=cloudflare
      - traefik.http.services.adguard.loadbalancer.server.port=80
networks:
  proxy:
    external: true
x-dockge:
  urls:
    - https://adguard.lan-t.cc
