---
name: yamllint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run yamllint
        uses: actionshub/yamllint@main
      - name: Prepare .env file
        run: cp example.env .env
      - name: Validate docker-compose.yml
        run: docker compose config --quiet
